#!/bin/bash

echo "🚨 修复 meet.linapp.fun nginx配置"
echo "=================================="

echo "请手动执行以下命令（需要sudo权限）："
echo ""
echo "# 1. 复制配置文件"
echo "sudo cp /home/meet/meet.linapp.fun.conf /etc/nginx/sites-available/meet.linapp.fun"
echo ""
echo "# 2. 启用站点"
echo "sudo ln -sf /etc/nginx/sites-available/meet.linapp.fun /etc/nginx/sites-enabled/"
echo ""
echo "# 3. 禁用默认站点（重要！）"
echo "sudo rm /etc/nginx/sites-enabled/default"
echo ""
echo "# 4. 测试配置"
echo "sudo nginx -t"
echo ""
echo "# 5. 重载nginx"
echo "sudo systemctl reload nginx"
echo ""
echo "# 6. 启动应用服务"
echo "sudo cp /home/meet/meet-app.service /etc/systemd/system/"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable meet-app"
echo "sudo systemctl start meet-app"
echo ""
echo "# 7. 检查状态"
echo "sudo systemctl status meet-app"
echo "curl http://meet.linapp.fun/"
echo ""
echo "=================================="
echo "问题原因：nginx默认配置拦截了所有请求"
echo "解决方案：禁用default站点，启用meet.linapp.fun配置"